name: my tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: first_test
        type: choice
        options:
          - first_test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: First test
        if: "${{ github.event.inputs.deployment_target == 'first_test' }}"
        run: pytest tests/test_button.py::test_button_exist
        continue-on-error: true